# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmanager',
            name='event_end_time',
            field=models.TimeField(default=datetime.time(11, 22, 4, 217269)),
        ),
        migrations.AddField(
            model_name='eventmanager',
            name='event_start_time',
            field=models.TimeField(default=datetime.time(11, 22, 4, 217269)),
        ),
        migrations.AlterField(
            model_name='eventmanager',
            name='event_date',
            field=models.DateField(default=datetime.date(2017, 11, 6)),
        ),
    ]
