# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20171106_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='city',
            field=models.CharField(choices=[('DURHAM', 'Durham'), ('RALEIGH', 'Raleigh')], default='Select', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='states',
            field=models.CharField(default='North Carolina', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventmanager',
            name='event_end_time',
            field=models.TimeField(default=datetime.time(14, 36, 54, 496757)),
        ),
        migrations.AlterField(
            model_name='eventmanager',
            name='event_start_time',
            field=models.TimeField(default=datetime.time(14, 36, 54, 496757)),
        ),
    ]
