# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20171106_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmanager',
            name='event_end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventmanager',
            name='event_start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
