# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20171106_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmanager',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
