# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_eventmanager_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocation',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
