# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20171108_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocation',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.EventManager'),
        ),
    ]
