# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20171110_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='venue',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
